---
title: "Why there are more species in several small patches vs few large patches:
  a multi-species modeling approach"
bibliography: sloss_bib.bib
csl: "ecology-letters.csl"

output:
  pdf_document: 
    includes:
      in_header: margins.sty
---

Leonardo A. Saravia ^1^^2^, Ulises Balza ^1^, Fernando Momo^3^^4^

1. Centro Austral de Investigaciones Científicas (CADIC-CONICET). Houssay 200 (9410), Ushuaia, Argentina.

2. Universidad Nacional de Tierra del Fuego (UNTDF), Yrigoyen 879 (9410), Ushuaia, Argentina

3. Instituto de Ciencias. Universidad Nacional de General Sarmiento. J.M. Gutierrez 1159 (1613), Los Polvorines, Argentina.

4. Departamento de Ciencias Básicas. Universidad Nacional de Luján. Rutas 5 y 7, (6700) Luján. Argentina.
        

## Abstract
 
As global biodiversity is rapidly declining due to habitat loss, it is important to determine how to protect it. The policies of many conservation agencies are still prioritizing the preservation of a single large habitat area (SL) vs. several small areas of the same size (SS), despite empirical support favouring SS. However, to date, most theories regarding this issue were based on single-species models. This work aims to explore spatial multi-species models to verify the SS > SL pattern and determine its causes. We used three types of models: a classical neutral, neutral with habitat selection, and a competitive hierarchical model.  All models have three parameters, namely extinction, reproduction, and dispersal distance. In the classical neutral model, species are equivalent and have the same parameters; when there is a reproduction event they send the propagule to a surrounding patch blindly, and if the patch is already occupied the propagule dies. In the neutral-with-habitat selection model, the propagules select an empty patch so their survival is ensured. In the hierarchical model, species have competitive dominance and more dominant ones can replace the less dominant with a replacement rate parameter. We use 100 species and start simulating the colonization of an empty area then we destroy a fixed amount of habitat using different regular patch sizes. The results for all models are almost always that SS retains more species than SL. The extinction of species in patches depends on the quotient between reproduction and extinction rates in relation to patch size. The only case when SL > SS is when dispersal is insufficient to connect patches, and patch size is smaller than the minimum to prevent extinction. If patch size is above the critical size to maintain local populations the SS > SL pattern is due to the sampling effect of aggregated species distribution combined with the reduction of dispersal ability of species. High dispersal rates produce homogenization of species distribution and a reduction of species richness and this is why habitat fragmentation by habitat loss retains more species when patches are smaller. The model predicts that if a set of species have more dispersal capabilities the SS effect would be lower than for species with less dispersal. 
 
## Keywords

## Introduction 

Global biodiversity is rapidly declining due to, among other factors, habitat loss [@Young2016;@Chase2020;@Newbold2015]. As habitat fragmentation occurs at the same time as habitat loss, the effects of both processes are difficult to disentangle [@Haddad2015]. Landscape connectivity and organism mobility are critical features for population persistence [@Taylor1993]. Starting from a landmark paper [@Diamond1975], conservation biologists engaged in the challenging task of recommending protection measures given the environmental crisis coupled with a lack of knowledge of most of the world’s biodiversity and limited funding for conservation. In that context, early recommendations claiming to follow ecological theory derived simple thumb rules to better design protected areas. However, as noted rapidly, species/area relationships do not have a clear association with fragmentation per se but mainly with overall habitat loss [@Simberloff1982].
Aiming to design better management practices, this led to a nearly 50-year Single Large vs Several Small (SLOSS) debate. While some authors argue that habitat loss is the most overwhelming effect on species loss, for others the complex factors arising from fragmentation further enhance species extinctions [@Fahrig2017;@Fletcher2018].  

The SLOSS debate has been an important academic and intellectual discussion in conservation biology. However, in practical implementation, numerous conservation agencies persist in prioritizing the safeguarding of extensive, contiguous habitat areas, often neglecting the protection of smaller patches of natural habitat [@Armsworth2018]. As an example, the current emphasis on 'rewilding' in Europe is geared towards the conservation and restoration of contiguous natural habitats, with a specified 'core area' of at least 10,000 hectares [@EuroparcFederation2013]. Similarly, conservation efforts for large water bodies take precedence, leaving small ponds or pondscapes largely excluded from priority considerations [@Hill2018].

While the overall habitat loss is widely accepted as a process leading to long-term biodiversity loss [@Keil2015;@Hodgson2011], the proposition that single large reserves retain more species than several small reserves of the same area (SL > SS) remain at a similar hierarchical state, even after several criticisms (reviewed in  @Fahrig2017). Empirical observational and experimental data shows the predominance of the opposite pattern (SS > SL) ever since the 80s and this fact has been reinforced to this day [@Simberloff1982; @Fahrig2020; @Hammill2020]. The actual processes driving it remain elusive and it is probably multi-causal. In that scenario, model simulations could produce useful hypotheses to better understand the processes leading to non-intuitive patterns of biodiversity loss. 

The SLOSS debate has been approached from several theoretical frameworks, but most of them were based on single-species models [@Fahrig2021]. Despite the long-standing discussion, there remains a notable scarcity of multi-species models explicitly designed to validate fragmentation theories. However, recent studies using spatially explicit simulations revealed that while high fragmentation leads to more local extinctions due to the reduced habitat size, at low levels of fragmentation, competitive exclusion is more prevalent, resulting in decreased diversity [@Rybicki2020].  

The recently proposed SLOSS cube hypothesis by @Fahrig2021 serves as a comprehensive framework summarizing existing Single Large or Several Small (SLOSS) predictions and empirical findings. This hypothesis posits that the condition where Single Large (SL) patches contribute more to biodiversity conservation than Several Small (SS) patches is contingent upon the simultaneous occurrence of specific conditions: a low between-patch movement rate, minimal impact of spreading-of-risk on population dynamics, and low species spatial clumping [@Fahrig2021].

This research aims to investigate multi-species spatially explicit models, incorporating a fixed level of habitat destruction, neutral and competitive community dynamics, diverse dispersal-related traits, and various geometries of habitat loss. The principal objective is to verify the conditions under which the SS > SL pattern holds and discern the underlying causes. Through this examination, we seek to contribute insights that can help determine if the conditions outlined in the SLOSS cube hypothesis are supported by our modeling approach.. 

Specifically, our approach involves simulating species retention under diverse fragmentation scenarios, all characterized by a fixed amount of habitat loss. We vary parameters such as patch sizes, community type (competitive or neutral), species dispersal capabilities, and the community's persistence status—whether it is near extinction and degraded or in a healthy state. This comprehensive exploration enables us to account for the interacting effects of habitat loss and a range of model parameters on species retention.

<!-- In that context, spatial-explicit multi-species modelling could be meaningful as several organisms retain dispersal distance and other dispersal-related life traits far consistently among species (quotes).-->

## Methods

### A spatial stochastic model

We developed a spatially explicit multi-species model to explore the relationship between habitat loss and species retention at the regional metapopulation level. In this model, space is discretized into a grid and only one individual of one species can occupy a particular position. Each position represents an area fixed by the investigator to mimic the real system. Time is continuous, so the update of the model is asynchronous. Sites are selected at random and to perform one complete time interval $J$ sites have to be updated, where $J$ is the size of the grid.

We use absorbing boundary conditions, which means that if an individual tries to disperse outside the grid it dies. The size of the community is given by *J = dimX* x *dimY*, where *dimX* and *dimY* are the dimensions of the grid. Thus *J* is the maximum number of individuals in the simulated area. As in a classical neutral model, there is a metacommunity, i.e. a regional species pool from where species migrate [@Hubbell2001]. All individuals have the same parameters and each species is assigned an indicator number. 

The model consists of three variations: a classical neutral model, a neutral model with habitat selection, and a competitive hierarchical model.

The classical neutral variation is where propagules (e.g., seeds) disperse passively and cannot actively choose their establishment site. During reproduction events, individuals disperse their propagules blindly to surrounding patches. If a patch is already occupied, the propagule fails to establish, resulting in its death. This variation captures the random dispersal and colonization processes typical of many plant species.

The neutral variation with habitat selection is where individuals can actively select suitable habitat patches. In this variation, propagules can choose unoccupied patches, ensuring their survival and successful establishment. This modification reflects the influence of habitat availability and selection on species colonization and persistence. By incorporating habitat selection, this variation better captures the ecological processes and behaviors of species that are capable of actively seeking out suitable habitats for reproduction and survival, like most animals

The competitive hierarchical variation extends the neutral variation with an additional layer of complexity by incorporating competitive interactions among species. Each species has an indicator number that determines its competitive dominance level, and more dominant species can replace less dominant ones at a specified replacement rate. This variation captures the influence of species interactions and competitive exclusion on species composition and abundance. It is particularly relevant for understanding communities where competitive interactions play a significant role in shaping species distributions and community structure (e.g., hummingbirds).

The following processes are included in the model: habitat loss, migration, reproduction, local dispersal, competition and death. After setting initial conditions the following events can happen:
  
(1) Habitat loss: the sites are marked as non-habitable, making them unsuitable for occupancy, up to a fixed percentage of degraded habitat. Different degradation scenarios are modeled:

    Regular degradation: Habitat is removed so that habitable patches form a regular pattern of squares with sides given by a habitat-size parameter. As the percentage of degraded habitat is constant varying the habitat-size parameter results in either a few large habitat patches (SL) or several small (SS).

    Random block degradation: Habitat square patches of a fixed size (habitat-size parameter) are located at random throughout the landscape. The sizes are identical to those used for regular degradation simulations, but it results in habitat patches that have a minimum size corresponding to the habitat-size but a maximum size that is bigger because habitat patches can overlap between them producing a larger patch. Then, we characterize this with the maximum habitat patch size. 

(2) With $migration-rate$ an individual of a species $i$ can migrate from the metacommunity. A random site on the border of the grid is selected and if it is empty and habitable the site is occupied[d].

(3) All individuals reproduce with $birth-rate$. When an individual reproduces the propagule disperses to the neighborhood with a dispersal kernel. Here we use an inverse power kernel [@Marco2011]:

    $d(x) =  \left(\frac{x}{x_{min}} \right)^{-\alpha}$ with $mean =\frac{\alpha-1}{\alpha-2}x_{min}$ where $\alpha > 1$ and $x \ge x_{min}$. 

    where $d(x)$ is the probability that an individual disperses a distance $x$ from the parent. In all cases, we used $x_{min} = 1$. We use as a parameter the mean $dispersal-distance$. 

    What happens to the propagule when arrives at the selected site is determined by the variation of the model simulated:

    a. Classical Neutral: If the target patch is already occupied by a species, the propagule perishes. 

    b. Neutral with Habitat Selection:  Propagules selectively target unoccupied patches for reproduction within the distance given by the dispersal kernel, ensuring their survival. 

    c. Competitive Hierarchical: Species are ranked by a competitive dominance hierarchy based on their internal identification   (id) number. If a dispersing propagule arrives at an occupied site, it will only be established if its id number is higher than the resident species. Otherwise, the propagule perishes without establishing. This simulates a system where dominant competitor species displace rarer or weaker species through interspecific competition during colonization of new sites. The hierarchy prioritizes species with lower id numbers as stronger competitors.
    
(4) Individuals die with a $death-rate$ independent of other events. 

For all simulations, we used a metacommunity of 100 species. The simulations start with the colonization of an empty habitat area. After 600 time steps, a fixed amount of 60% of habitat is subsequently subjected to destruction, employing regular or random block degradation to mimic habitat fragmentation due to habitat loss. <!-- why we don't use completely random degradation patterns -->

| $\lambda$ | Dispersal Distance | Habitat Patch size |
| --------: | ---------:         | ---------:         |
| 1.7       | 1.1                | 3                  |
| 2.0       | 1.2                | 9                  |
| 3.0       | 1.5                | 29                 |
| 4.0       | 2                  | 61                 |
|           | 3                  |                    |

Table: Parameter values utilized in simulations, with factorial combinations of these parameters employed to run simulations. The symbol $\lambda$ represents the ratio of growth rate to death rate. "Dispersal distance" denotes the mean of the power law dispersal kernel, while "Habitat patch size" indicates the side length of habitat patches modeled as squares. Both the dispersal distance and habitat patch size are measured in grid cells.


The parameters encompass a range of $growth-rates$ while holding the $death-rate$ fixed at 1. In this model, the relationship between these parameters, $\lambda = growth-rate / death-rate$, is the main determinant of the fate of an individual of a species. In similar non-spatial models, this relationship must exceed 1 for a species to persist. Thus we used a minimum $\lambda$ of 1.7, we also fixed the $migration-rate$ at 0.0001. We simulate each model variant using the parameters shown in Table 1. For the neutral classical version only, we also simulate random block habitat patterns. For each combination of parameters we ran 30 simulations up to 1500 time steps and recorded the number of species, the Shannon Diversity index [@Magurran2013] and the total number of individuals. For some representative combinations of parameters, we take snapshots of the model output showing the typical dynamics on time of the 3 recorded quantities and the rank abundance species distribution [@Newman2005; @May1975]  

The classical neutral model and the habitat selection model could represent endpoints on a continuum of models where the matrix is either completely adverse or not adverse but still unsuitable for reproduction. In the habitat selection model, individuals can search across both the matrix and suitable habitat until they find an empty place. In contrast, for the classical neutral model, individuals have limited or no capacity to search, and the matrix is necessarily detrimental because it increases the probability of death by landing on an unsuitable site.

The model was developed in Netlogo 6.3.0 and the model source code is available at Github <https://github.com/lsaravia/DynamicForestExtinction>, the Overview, Design concepts, Details (ODD), protocol for describing individual-based models is included within the model source code [@Grimm2010]. We performed the simulations and analysis using R version 4.3.1 [@RCoreTeam2023], the R source code to perform simulations and analysis is located at <https://github.com/EcoComplex/multiSLOSS>. 

## Results

In our neutral model simulations with a migration rate of $0.0001$ and regular habitat patterns, species richness varied with habitat patch sizes, influenced by dispersal distance and the $\lambda$ parameter (Figure 1). Species richness increased with $\lambda$, with the highest richness at smaller patch sizes for higher $\lambda$ values. Conversely, a $\lambda$ of 3 or less showed reduced richness at the smallest patch sizes for lower dispersal distances. In these cases, only migrants survive in the smallest patches, and no local populations are established (Figures S13 & S14).
The interplay of dispersal distances, habitat sizes, and $\lambda$ impacts community survival and species richness. For $\lambda < 4$ this suggests a threshold patch size influenced by these 3 parameters, for $\lambda = 4$ patch size decreases species richness. The differences between increasing $\lambda$'s almost disappear when dispersal distance is higher. Extended dispersal distances could enhance species survival in scenarios with low $\lambda$ and smaller patches but reduce richness beyond a certain threshold. Similar patterns are evident for Shannon diversity (Figure 2). 

![Relationship between the number of species and habitat patch size for varying dispersal distances and $\lambda$ parameter (across panels). Simulations were performed using a neutral model with a constant migration rate (0.0001). Following 200 time steps of the model, 60% of the habitat was destroyed, rendering it unavailable for the species. The destruction of habitat resulted in the formation of regular patterns, where all remaining patches exhibited equal sizes.](Figures/Species_Habitat_Dispersal_Lambda_regular.png)

![Relationship between Shannon Diversity and habitat patch size for varying dispersal distances and $\lambda$ parameter (across panels). Simulations were performed using a neutral model with a constant migration rate (0.0001). Following 200 time steps of the model, 60% of the habitat was destroyed, rendering it unavailable for the species. The destruction of habitat resulted in the formation of regular patterns, where all remaining patches exhibited equal sizes.](Figures/Shannon_Habitat_Dispersal_Lambda_regular.png)

For the simulations conducted with randomly arranged block habitat patterns, the patches exhibit variable sizes, following a distribution with a minimum size determined by the patch-size parameter and a larger maximum size determined by the superposition of several patches (Figures S9 - S11). The overall pattern is analogous to the regular case, with a peak in richness occurring for intermediate patch sizes. However, for values of $\lambda$ higher than 2, the maximum richness is observed at the smaller habitat patch size (Figure S1 & S2). The patches in the random block simulations are generally larger, resulting in lower species richness and diversity, except for the minimum patch size (Figure S7 & S8). Supplementary material (Figures S9 & S32) includes examples of simulations with random block and regular habitat patterns. In these figures, it is evident that for the minimum patch size, only migrants survive in regular habitat patterns with neutral and hierarchical models.

![Relationship between the number of species and habitat patch size for different versions of the model (across panels) and varying dispersal distances. The neutral is the classical neutral model, species are equivalent and have the same parameters; in the hierarchical model, species have competitive dominance and more dominant ones can replace the less dominant; the neutral-with-habitat-selection model, is a neutral model but propagules search an empty patch so their survival is ensured. Simulations were performed using a fixed growth rate (2), migration and replacement rate of 0.0001 and 0.3 respectively. Following 200 time steps of the model, 60% of the habitat was destroyed, rendering it unavailable for the species. The destruction of habitat resulted in the formation of regular patterns, where all remaining patches exhibited equal sizes.](Figures/AcrossBehav_Species_Dispersal_Lambda2_regular.png)

![Relationship between Shannon Diversity and habitat patch size for different versions of the model (across panels) and varying dispersal distances. The neutral is the classical neutral model, species are equivalent and have the same parameters; in the hierarchical model, species have competitive dominance and more dominant ones can replace the less dominant; the neutral-with-habitat-selection model, is a neutral model but propagules search an empty patch so their survival is ensured. Simulations were performed using a fixed growth rate (2), migration and replacement rate of 0.0001 and 0.3 respectively. Following 200 time steps of the model, 60% of the habitat was destroyed, rendering it unavailable for the species. The destruction of habitat resulted in the formation of regular patterns, where all remaining patches exhibited equal sizes.](Figures/AcrossBehav_Shannon_Dispersal_Lambda2_regular.png)

Comparing the three versions of the model at $\lambda =2$, for higher dispersal the neutral model tends to have higher richness and Shannon diversity at higher patch sizes, followed by the hierarchical model and the neutral-with-habitat-selection model (Figures 3 & 4). At the lowest patch size, only in the neutral-with-habitat-selection have populations that can survive, because in the other model versions the individuals observed are migrants that cannot establish local populations and become extinct (See Figures S5 - S15). Thus an intermediate patch size with a maximum species richness is not observed for this model. Is also clearly observed that for the hierarchical model, there is a strong dominance of the more competitive species where Shannon Diversity is very low for a higher dispersal rate (Figure 4 & S23).

Examples of the spatial patterns of species and habitat distributions are illustrated in Figures 5 and S9-S32. Simulations with the neutral model depict the species' spatial distribution before fragmentation (Figure 5 A & B) and after fragmentation (Figure 5 C to F), with habitat destruction represented in purple areas. Immediately after fragmentation, the species' spatial distributions closely resemble those before habitat destruction, but then the patch compositions diverge. The divergence in patch species composition is more pronounced in the hierarchical model, where small patches tend to be dominated by one species (Figures S17 - S24). The effect of the minimum patch size for survival is also observed (Figure 5 E).

![Examples of species spatial patterns before and after fragmentation for the neutral model are illustrated. Different shades from dark green to white represent distinct species, with the destroyed habitat depicted in purple. Simulations were conducted with a fixed growth rate ($\lambda=2$), a migration rate of 0.0001, and a dispersal distance of 1.5. A. & B. showcase spatial patterns before fragmentation. C. & D. depict spatial patterns after fragmentation, where 60% of the habitat was destroyed, with patch sizes of 3 (C) and 29 (D). In these cases, the significance of the species' spatial distribution before fragmentation becomes evident. E. & F. display spatial patterns after 600 time steps, illustrating the extinction of populations at smaller patch sizes (E).](Figures/ModelSpatialPatternComparison.png)

## Discussion

Our research contributes to the ongoing SLOSS debate in conservation biology, offering new insights based on our model findings. Consistent with previous studies, the results from our simulations primarily support the SS > SL pattern for species retention, as observed across various model scenarios [@Fahrig2020]. This trend underlines the greater efficacy of multiple smaller habitats in preserving species diversity compared to a single large habitat under equal conditions of habitat loss. A critical factor in this dynamic is the balance between reproduction and extinction rates ($\lambda$ parameter) and dispersal relative to the size of the habitat patches, influencing their role as sources of propagules. Notably, the SL > SS scenario emerges only when dispersal limitations prevent patch connectivity, and patch sizes are above a certain threshold to prevent local extinctions, aligning with Rybicki's [-@Rybicki2020] findings.

In neutral models, where species are considered equivalent, one species, by chance, tends to dominate a patch (Hubbell, 2001). Consequently, in fragmented landscapes, once a species increases its density, the likelihood of another species replacing it is low. With more patches, the probability of having a greater number of species is heightened. This effect is further amplified when individuals can actively select their habitat, leading to increased survival of propagules. Consequently, fragmentation exhibits a positive influence on the number of species in such scenarios.

For competitive communities, there is a higher probability that different species dominate different smaller patches, compared with a bigger patch. Thus, again fragmentation has a positive effect on the number of species, this effect is called stochastic divergence [@Riva2023]. In smaller patches there is an increase in extinction risk because they support smaller populations [@Laurance2002;@Shafer1995], however as patches become smaller they also become more numerous, reducing the probability of extinction over the entire set of patches due to spreading the risk effect [@Crowley1977]. The combination of these two effects, the stochastic divergence and the risk effect, explain the highest number of species with patch size over the threshold of species survival. 

This positive effect is counteracted by dispersal, high dispersal rates tend to a homogenization of species distributions, so fragmented landscapes tend to be more like not fragmented ones reducing overall species richness. This pattern was particularly pronounced for species combining high dispersal capabilities with competitive strengths, indicating a complex interplay between dispersal, competitive interactions, and species diversity [@Fahrig2020]. 

Edge effects are present in the neutral and hierarchical models, but not in the neutral-with-habitat-selection model. In the first two models, the edge effect is because individuals in the patch's border have fewer neighbors and the probability of extinction is higher.  In the neutral-with-habitat-selection model, the edge effect is not present because the individuals search for empty patches, so the individuals on the border of the patch have the same probability of extinction as the individuals in the interior of the patch. Thus when patches are smaller the edge proportion is higher and the edge effect is more important, but this plays a more important role in the minimal patch size for the survival of species than for the species richness.

The spatial arrangement of habitat patches, contrary to some expectations, did not produce different species richness patterns regarding habitat patch size. The exceptions are stressed communities---represented in our models with lowest $\lambda$--- with low dispersal may have a continuous increment of richness with patch size, observed only in random block degradation patterns. This could be related to the optimal patch size for random block habitat loss patterns, which tends to be higher than for regular patterns, so we could hypothesize that the optimal was outside the simulated range for these stressed communities. The aggregation of patches in the random block pattern (implies aggregation of the degraded habitat) could be positive if individual habitat patches are very small because it allows some patches to surpass the minimum size required for survival. For bigger patch sizes it could be detrimental because the aggregation produces even bigger patch sizes that decrease species richness. A similar effect was observed on experimental landscapes [@Fletcher2023], aggregated patterns of habitat loss are detrimental to patch occupancy and eventually could produce the same effects observed in our models about richness. 

Naturally, there are limitations to our modeling work. Firstly, it is important to note that more research is needed to apply our to determine the effect of fragmentation in real-world communities. We assume that all species have the same parameters, thus hypothetically determining these parameters for all the species, and using the mean to determine the responses to fragmentation would render an approximate value for the effects and thresholds. Also, an improved version of the model with different values of the parameters for each species could be developed and compared with the neutral model. The effects of fragmentation could be influenced by many other ecological/behavioural characteristics of the species not considered in the model, including environmental heterogeneity, matrix permeability, and individual’s cost of dispersal, among others. Further, the size of the focal landscape compared to dispersal distances, which determines the scale of the dynamics, could influence quantitative results [@Rybicki2020]. Additionally, the application of mean parameter values in relatively simple multispecies models has been successfully employed and tested for predicting species biomass, as demonstrated by @Fort2018. 

In previous simulation studies, the importance of fragmentation was demonstrated to be pronounced when the habitat amount is low, approximately around 10% [@Hanski2015; @Rybicki2013]. However, experimental studies have observed that with habitat levels around 10-20%, the impact of fragmentation can be positive or show an intermediate maximum [@Loke2019; @With2016]. When habitat amounts are lower (e.g., 7%), the arrangement of patches appears to have no significant effect. Interestingly, our study replicated similar patterns even with a 40% habitat amount. Moreover, other studies employing comparable habitat amounts (32%) also reported higher species richness with increased fragmentation [@Rybicki2020].

One novel aspect of our model is that it considers communities that are assembled from a metacommunity in which individuals migrate to an empty habitat. After the number of species is stabilized the habitat is fragmented. This scenario is deemed more realistic than having all species initially present with random patterns in an already fragmented habitat  [@Rybicki2020]. This could be more important the more heterogeneous was species spatial distribution pattern before fragmentation, as the cube hypothesis states.

In terms of the cube hypothesis, low between-patch movement, minimal impact of spreading-of-risk on population dynamics, and low species spatial clumping are needed for SL > SS. In our model dispersal distance increases between patch movements, but for higher dispersal distances the sizes of the patches are less important and the relationship tends to be SS = SL. Spreading-of-risk is influenced by $\lambda$, which represents the relationship between the growth and death rates. For smaller $\lambda$, spreading-of-risk becomes more significant because the probability of local extinction is higher. A very low dispersal distance combined with low $\lambda$ favors SL > SS up to a threshold in patch size, beyond which SL = SS. The spatial clumping of species is influenced by the dispersal distance; a higher dispersal distance produces less clumpiness. However, this is confounded with patch movement, making it challenging to disentangle the effect. Therefore, the results of our model are generally compatible with the cube hypothesis.

Our findings support Fahrig's [-@Fahrig2021] conclusion that conditions favoring SL > SS are limited and infrequently observed in nature. Under conditions of adequate patch size and dispersal capabilities, the SS scenario typically retains more species. This underscores the ecological significance of smaller habitat patches in maintaining biodiversity and landscape connectivity [@Yan2021; @Manning2006; @Shafer1995]. Our results thus challenge the conventional preference for larger reserves in conservation planning and support the paradigm shift in conservation towards considering sets of many small patches generally having higher biodiversity than sets of few large patches [@Riva2023]. The model's primary outcomes could be validated using empirical data by assessing the prediction that species with greater dispersal capabilities would exhibit a lower SS effect compared to species with limited dispersal.

In conclusion, we believe our study adds valuable perspectives to the SLOSS debate, illustrating the complexities of habitat fragmentation and species conservation. While our model has inherent limitations, it provides a useful framework for understanding key ecological processes. Future research should aim to extend these findings to more diverse ecological settings and incorporate how heterogeneity between species influence biodiversity in fragmented landscapes.


## Acknowledgments

## References
